/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.QueimadasDAO;
import Model.MetodosOrdenacao;
import Model.Queimadas;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kazuo
 */
public class Consulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
        QueimadasDAO QueiDAO = new QueimadasDAO();
        montaTabelaCliente(QueiDAO.read());
    }

    private void montaTabelaCliente(List<Queimadas> dados) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.getDataVector().removeAllElements();
        modelo.setNumRows(0);

        for (Queimadas q : dados) {
            modelo.addRow(new Object[]{
                q.getDatahora(),
                q.getSatelite(),
                q.getPais(),
                q.getEstado(),
                q.getMunicipio(),
                q.getBioma(),
                q.getDiasemchuva(),
                q.getPrecipitacao(),
                q.getRiscofogo(),
                q.getLatitude(),
                q.getLongitude(),
                q.getFrp(),
                q.getId()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "datahora", "satelite", "país", "estado", "municipio", "bioma", "diassemchuva", "precipitacao", "riscodefogo", "latitude", "longitude", "frp", "id"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Data", "satelite", "pais", "estado", "municipio", "bioma", "diasSemChuva", "preciptacao", "riscoDeFogo", "Latitude", "Longitude", "Frp", "Id", "", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BubbleSort", "Selection Sort", "Quick Sort" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addContainerGap(579, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(879, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(294, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    }//GEN-LAST:event_jComboBox2ActionPerformed
    private void Ordena(String tipo, List<Queimadas> dados) {
        MetodosOrdenacao ordenador = new MetodosOrdenacao();

        switch (tipo) {
            case "BubbleSort":

                long startDesordenado = System.currentTimeMillis();
                ordenador.bubbleSort(dados, String.valueOf(jComboBox1.getSelectedItem()));
                long elapsed = System.currentTimeMillis() - startDesordenado;
                JOptionPane.showMessageDialog(null, "Bubble Sort: \n Demorou: " + elapsed + " ms");
                break;
            case "Selection Sort":
                long startDesordenado1 = System.currentTimeMillis();
                ordenador.selection(dados, String.valueOf(jComboBox1.getSelectedItem()));
                long elapsed2 = System.currentTimeMillis() - startDesordenado1;
                JOptionPane.showMessageDialog(null, "Selection Sort: \n Demorou: " +elapsed2 + "ms");
                break;
            case "Quick Sort":
                long startDesordenado3 = System.currentTimeMillis();
                ordenador.quick(dados, String.valueOf(jComboBox1.getSelectedItem()), 0, dados.size() - 1);
                long elapsed3 = System.currentTimeMillis() - startDesordenado3;
                JOptionPane.showMessageDialog(null, "Quick Sort:\n Demorou: " + elapsed3 + "ms");
                break;
                
        }
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        QueimadasDAO QueiDAO = new QueimadasDAO();
        List<Queimadas> dados = QueiDAO.read();
        Ordena(String.valueOf(jComboBox2.getSelectedItem()), dados);
        montaTabelaCliente(dados);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
